#!/usr/bin/env bash
# create cryptopt-asms
sfile="$(dirname "${0}")/asm.S"
test -e "${sfile}" && rm "${sfile}"
count=${1:-1}

base_path=~/cryptopt/results/bitcoin-core/
clean_file_name=".last_clean_run"

# get best asms
for sym in secp256k1_fe_mul_inner secp256k1_fe_sqr_inner; do
  p=${base_path}${sym}
  test ! -d "${p}" && echo "couldn't find directory ${p}" && continue

  clean_file="${p}/${clean_file_name}"
  test ! -e "${clean_file}" && echo "couldn't find ${clean_file}" && continue

  fast_asm_file=${p}/$(sort --general-numeric-sort "${clean_file}" |
    sed --regexp-extended --silent '/^[[:digit:]\.]+ [[:alnum:]_]+\.asm$/p' |
    sed --silent "${count}p" |
    awk '{print $2 }')

  test ! -e "${fast_asm_file}" && echo "there is no fastest impl >>${p}<< for ${sym}" && continue

  ~/cryptopt/modules/scripts/convert/intel2att.sh --crypto-namespace "${fast_asm_file}" >>"${sfile}"
done
